#!/usr/bin/env bash

# Path to the bash it configuration
export BASH_IT="$HOME/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='ratlaw'

# Set my editor and git editor
export EDITOR='/usr/bin/vim'
export GIT_EDITOR="$EDITOR"

# PYTHONSTARTUP
export PYTHONSTARTUP="$HOME/.pythonrc.py"

# force term
if [[ "$TERM" = "xterm" || "$TERM" = "screen" ]]; then
    export TERM="$TERM-256color"
fi

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

if which go 2&>1 >/dev/null; then
    export GOPATH="$HOME/go"
    export PATH="$PATH:$GOPATH/bin"
fi

# Load Bash It
source "$BASH_IT/bash_it.sh"
