#!/bin/fish
# Attach to existing ssh session

if [ -z "$argv[1]" ]
    set profile "main"
else
    set profile "$argv[1]"
end

# ssh auth sock for tmux
if [ -z "$TMUX" ]
  if [ ! -z "$SSH_TTY" ]
      if [ ! -z "$SSH_AUTH_SOCK" ]
          ln -sf "$SSH_AUTH_SOCK" "$HOME/.wrap_auth_sock_$profile"
      end
      set -x SSH_AUTH_SOCK "$HOME/.wrap_auth_sock_$profile"
  end
end

set -x TERM screen-256color
# Attach to running tmux session
if tmux has-session -t "$profile" ^/dev/null
    exec tmux attach-session -t "$profile"
else
    exec tmux new-session -s "$profile"
end
