#!/bin/bash
# Attach to existing ssh session
has_session="tmux has-session"
attach="tmux attach"
new="tmux new"

export TERM="screen-256color"
# Attach to running tmux session
if [ "$1" ]
then
    has_session="$has_session -t $1"
    attach="$attach -t $1"
    new="$new -s $1"
fi

if eval $has_session
then
    exec $attach
else
    exec $new
fi
